TRAINING_DATA = [
    ("not breathing unconscious no pulse", "cardiac_arrest", 3),
    ("cardiac arrest heart stopped no pulse defibrillator", "cardiac_arrest", 3),
    ("severe stroke unable to speak paralyzed face drooping arm", "stroke", 3),
    ("massive internal bleeding unconscious pale cold skin", "trauma", 3),
    ("severe head injury unconscious bleeding from ear nose", "trauma", 3),
    ("anaphylactic shock difficulty breathing throat swelling face", "allergic_reaction", 3),
    ("choking unable to breathe turning blue lips cyanosis", "choking", 3),
    ("drowning unconscious not breathing pulled from water", "drowning", 3),
    ("severe burns over 50 percent body charred skin", "burns", 3),
    ("uncontrolled seizure not stopping five minutes status", "seizure", 3),
    ("heart attack chest pain radiating left arm sweating", "cardiac", 3),
    ("sudden collapse unconscious no response on floor", "cardiac", 3),
    ("severe allergic reaction throat closing cannot swallow", "allergic_reaction", 3),
    ("gunshot wound chest bleeding heavily unresponsive", "trauma", 3),
    ("stabbing wound deep abdomen bleeding profusely", "trauma", 3),
    ("overdose unconscious slow breathing blue lips cyanosis", "poisoning", 3),
    ("severe respiratory failure oxygen not helping declining", "respiratory", 3),
    ("multiple organ failure septic shock low pressure", "sepsis", 3),
    ("eclampsia seizure pregnancy unconscious fitting", "obstetric", 3),
    ("aortic dissection sudden severe tearing chest back pain", "cardiac", 3),
    ("massive stroke sudden paralysis one side body", "stroke", 3),
    ("carbon monoxide poisoning unconscious multiple victims", "poisoning", 3),
    ("hanging found unconscious not breathing marks neck", "trauma", 3),
    ("severe electric shock unconscious burns entry exit", "electric", 3),
    ("crush injury trapped debris unconscious bleeding", "trauma", 3),
    ("ruptured ectopic pregnancy severe pain bleeding shock", "obstetric", 3),
    ("diabetic coma unconscious not responding glucose low", "diabetic", 3),
    ("meningitis high fever stiff neck rash unconscious", "infection", 3),
    ("pulmonary embolism sudden chest pain cannot breathe blue", "respiratory", 3),
    ("severe asthma attack not responding inhaler blue lips", "respiratory", 3),
    ("brain hemorrhage sudden severe headache unconscious vomiting", "neurological", 3),
    ("ventricular fibrillation heart rhythm stopped", "cardiac", 3),
    ("severe sepsis confusion low blood pressure high fever", "sepsis", 3),
    ("tension pneumothorax collapsed lung severe breathing", "respiratory", 3),
    ("massive hemorrhage uncontrolled bleeding trauma", "trauma", 3),
    ("spinal cord injury complete paralysis below waist", "trauma", 3),
    ("status epilepticus continuous seizure not stopping", "seizure", 3),
    ("severe hypothermia body temperature dangerously low", "environmental", 3),
    ("acute liver failure jaundice confusion bleeding", "organ_failure", 3),
    ("acute kidney failure no urine output confusion", "organ_failure", 3),
    ("child not breathing blue cyanotic unresponsive", "pediatric", 3),
    ("newborn not breathing after birth blue not crying", "pediatric", 3),
    ("drowning child unconscious pulled from pool", "drowning", 3),
    ("fall three story building multiple injuries unconscious", "trauma", 3),
    ("severe allergic bee sting throat closing unconscious", "allergic_reaction", 3),
    ("chemical explosion burns face eyes chest unconscious", "burns", 3),
    ("motorcycle accident head injury unconscious bleeding road", "trauma", 3),
    ("fire victim smoke inhalation unconscious burns", "burns", 3),
    ("heroin overdose not breathing pinpoint pupils blue", "poisoning", 3),
    ("severe preeclampsia seizure pregnancy unresponsive", "obstetric", 3),
    ("ruptured appendix peritonitis rigid abdomen shock", "abdominal", 3),
    ("acute pancreatitis severe shock low pressure vomiting blood", "abdominal", 3),
    ("bowel perforation sudden severe pain rigid abdomen shock", "abdominal", 3),
    ("severe hyponatremia sodium low seizure confusion", "metabolic", 3),
    ("thyroid storm high fever rapid heart rate confusion", "endocrine", 3),
    ("addison crisis low blood pressure vomiting confusion", "endocrine", 3),
    ("thunderclap headache worst ever subarachnoid hemorrhage", "neurological", 3),
    ("child febrile seizure prolonged unconscious high fever", "pediatric", 3),
    ("placental abruption severe bleeding pregnancy shock", "obstetric", 3),
    ("cord prolapse emergency delivery limb out", "obstetric", 3),
    ("construction accident fall scaffolding unconscious bleeding", "trauma", 3),
    ("electrocution high voltage unconscious burns extensive", "electric", 3),
    ("near drowning ocean rescue unconscious breathing barely", "drowning", 3),
    ("avalanche victim buried hypothermia unconscious", "environmental", 3),
    ("lightning strike unconscious burns entry exit points", "electric", 3),
    ("multiple stab wounds chest abdomen unconscious blood loss", "trauma", 3),
    ("industrial chemical inhalation respiratory failure", "poisoning", 3),
    ("pediatric respiratory distress infant cyanosis retractions", "pediatric", 3),
    ("ruptured spleen blunt trauma abdomen shock pale", "trauma", 3),
    ("massive pulmonary hemorrhage coughing blood unconscious", "respiratory", 3),
    ("severe burns airway inhalation stridor unconscious", "burns", 3),
    ("pediatric intussusception screaming drawing knees shock", "pediatric", 3),
    ("meningococcal septicemia rash not blanching fever shock", "sepsis", 3),
    ("severe malaria cerebral unconscious high fever seizure", "infection", 3),
    ("acute epiglottitis drooling stridor cannot swallow shock", "ent", 3),
    ("cardiac tamponade muffled heart sounds low pressure", "cardiac", 3),
    ("massive stroke brainstem unconscious eyes fixed", "stroke", 3),
    ("severe hypertensive emergency grade four papilledema seizure", "cardiac", 3),
    ("ruptured ovarian cyst severe bleeding shock pale", "obstetric", 3),
    ("amniotic fluid embolism sudden collapse delivery", "obstetric", 3),
    ("severe anaphylaxis epinephrine given still deteriorating", "allergic_reaction", 3),
    ("open skull fracture brain matter visible unconscious", "trauma", 3),
    ("flail chest multiple rib fractures paradoxical breathing", "trauma", 3),
    ("traumatic aortic rupture deceleration injury shock", "trauma", 3),
    ("bilateral tension pneumothorax absent breath sounds shock", "respiratory", 3),
    ("severe acidosis pH less than seven confusion coma", "metabolic", 3),
    ("pediatric epiglottitis cannot swallow drooling stridor", "pediatric", 3),
    ("malignant hyperthermia temperature 42 degrees surgery", "endocrine", 3),
    ("neuroleptic malignant syndrome rigidity fever unconscious", "psychiatric", 3),
    ("serotonin syndrome agitation hyperthermia seizure", "psychiatric", 3),
    ("severe tricyclic overdose seizure QRS wide collapse", "poisoning", 3),
    ("organophosphate poisoning SLUDGE syndrome seizure", "poisoning", 3),
    ("cyanide poisoning bitter almonds smell unconscious", "poisoning", 3),
    ("severe methanol poisoning vision loss confused acidosis", "poisoning", 3),
    ("child non accidental injury bruising suspicious unconscious", "pediatric", 3),
    ("child foreign body airway complete obstruction blue", "pediatric", 3),
    ("post cardiac surgery tamponade low output shock", "cardiac", 3),
    ("severe autonomic dysreflexia spinal cord hypertension", "neurological", 3),
    ("acute angle closure glaucoma severe pain vision loss", "eye", 3),
    ("central retinal artery occlusion sudden vision loss painless", "eye", 3),
    ("severe hypokalemia paralysis respiratory failure", "metabolic", 3),
    ("severe hyperkalemia peaked T waves cardiac arrest risk", "metabolic", 3),
    ("acute adrenal crisis collapse low sodium shock", "endocrine", 3),
    ("pheochromocytoma crisis severe hypertension headache", "endocrine", 3),
    ("massive PE saddle embolus shock right heart failure", "respiratory", 3),
    ("severe ARDS hypoxia despite maximum oxygen", "respiratory", 3),
    ("drowning pool unconscious child bystander CPR", "drowning", 3),
    ("severe hypothermia temperature 28 degrees no pulse", "environmental", 3),
    ("heat stroke core temperature 41 confusion seizure", "environmental", 3),
    ("severe frostbite bilateral feet hands gangrene developing", "environmental", 3),
    ("blast injury IED multiple penetrating wounds", "trauma", 3),
    ("crush syndrome hours entrapment compartment syndrome", "trauma", 3),
    ("traumatic brain injury GCS 3 pupils fixed dilated", "trauma", 3),
    ("spinal cord complete C4 injury ventilation required", "trauma", 3),
    ("massive transfusion protocol activation blood loss", "trauma", 3),
    ("penetrating eye injury globe rupture vision loss", "eye", 3),
    ("severe chemical burn face airway involvement", "burns", 3),
    ("white phosphorus burns spreading oxygen makes worse", "burns", 3),
    ("high voltage burn internal organs affected", "electric", 3),
    ("lightning strike cardiac arrest multiple victims", "electric", 3),
    ("severe pre-hospital RSI intubation failed airway", "respiratory", 3),
    ("post resuscitation ROSC but unconscious cooling protocol", "cardiac", 3),
    ("STEMI massive anterior blockage cardiogenic shock", "cardiac", 3),
    ("ruptured AAA abdominal aortic aneurysm shock", "vascular", 3),
    ("mesenteric ischemia bowel infarction peritonitis shock", "abdominal", 3),
    ("volvulus complete obstruction peritonitis shock", "abdominal", 3),
    ("severe DIC disseminated intravascular coagulation bleeding", "hematological", 3),
    ("acute leukemia blast crisis bleeding fever neutropenic", "hematological", 3),
    ("sickle cell crisis severe vaso-occlusive acute chest", "hematological", 3),
    ("severe thrombocytopenia bleeding brain platelet zero", "hematological", 3),
    ("hemophilia severe bleed joint brain life threatening", "hematological", 3),
    ("severe preterm labour 24 weeks cord prolapse", "obstetric", 3),
    ("uterine rupture sudden pain scar site fetal distress", "obstetric", 3),
    ("massive postpartum haemorrhage atony four litres", "obstetric", 3),
    ("shoulder dystocia baby stuck cannot deliver", "obstetric", 3),
    ("neonatal respiratory distress severe hypoxia", "pediatric", 3),
    ("pediatric sepsis shock purpuric rash", "pediatric", 3),
    ("child drowning bath unconscious parent found", "drowning", 3),
    ("child house fire smoke inhalation burns face", "burns", 3),
    ("infant shaken baby SDH retinal hemorrhage seizure", "pediatric", 3),
    ("status asthmaticus child silent chest no wheeze", "pediatric", 3),
    ("pediatric anaphylaxis nut allergy unconscious", "pediatric", 3),
    ("neonatal seizure first day of life glucose low", "pediatric", 3),
    ("premature baby born ambulance not breathing", "pediatric", 3),
    ("child meningitis purpuric rash high fever stiff neck", "pediatric", 3),
    ("ROSC post arrest unconscious targeted temperature", "cardiac", 3),
    ("cardiogenic shock LVEF 10 percent mechanical support", "cardiac", 3),
    ("massive haemoptysis blood litres coughing respiratory", "respiratory", 3),
    ("tracheal rupture subcutaneous emphysema intubation failed", "respiratory", 3),
    ("severe bronchospasm anaphylaxis unresponsive epinephrine", "respiratory", 3),
    ("altitude pulmonary oedema HACE HAPE combined severe", "environmental", 3),
    ("near hanging incomplete found early unconscious", "trauma", 3),
    ("severe rhabdomyolysis crush myoglobin renal failure", "trauma", 3),
    ("traumatic haemothorax massive blood chest shock", "trauma", 3),
    ("open book pelvic fracture massive haemorrhage", "trauma", 3),
    ("bilateral femur fractures massive blood loss shock", "trauma", 3),
    ("strangulation assault marks neck unconscious", "trauma", 3),
    ("penetrating abdominal trauma evisceration bowel out", "trauma", 3),
    ("severe eye alkali burn limbal ischemia vision loss", "eye", 3),
    ("acute retinal artery occlusion embolus sudden loss", "eye", 3),
    ("optic neuritis sudden vision loss severe", "eye", 3),
    ("cavernous sinus thrombosis eye proptosis fever septic", "eye", 3),
    ("severe hyperglycaemia HHS osmolarity high unconscious", "diabetic", 3),
    ("fulminant hepatic failure coagulopathy encephalopathy", "organ_failure", 3),
    ("end stage renal failure fluid overload pulmonary oedema", "organ_failure", 3),
    ("severe cardiomyopathy acute decompensation shock", "cardiac", 3),
    ("right heart failure massive PE obstructive shock", "cardiac", 3),
    ("severe aortic stenosis syncope on exertion critical", "cardiac", 3),
    ("complete heart block rate 20 unconscious no output", "cardiac", 3),
    ("Wolff Parkinson White SVT degenerated VF collapse", "cardiac", 3),
    ("hypertrophic cardiomyopathy young athlete collapse sport", "cardiac", 3),
    ("commotio cordis chest blow VF young player sport", "cardiac", 3),
    ("severe mitral regurgitation acute pulmonary oedema", "cardiac", 3),
    ("tension haemopneumothorax tracheal deviation shock", "trauma", 3),
    ("traumatic diaphragm rupture bowel chest", "trauma", 3),
    ("severe facial trauma airway compromised bleeding", "trauma", 3),
    ("C spine fracture unstable dislocation paralysis", "trauma", 3),
    ("thoracic aorta injury deceleration widened mediastinum", "trauma", 3),
    ("kidney laceration haematuria shock flank pain trauma", "trauma", 3),
    ("liver laceration blunt trauma shock haemoperitoneum", "trauma", 3),
    ("splenic laceration grade five uncontrolled bleeding", "trauma", 3),
    ("bladder rupture pelvic fracture haematuria peritonitis", "trauma", 3),
    ("urethral injury pelvic fracture cannot pass urine blood", "trauma", 3),
    ("severe maxillofacial trauma airway blood cannot intubate", "trauma", 3),
    ("hanging complete spinal cord injury C2 no breathing", "trauma", 3),
    ("traumatic pneumocephalus brain air CT scan", "trauma", 3),
    ("severe aspiration pneumonia oxygen 70 percent intubation", "respiratory", 3),
    ("Ludwig angina floor mouth swelling airway threatened", "ent", 3),
    ("retropharyngeal abscess stridor fever airway threatened", "ent", 3),
    ("parapharyngeal abscess mediastinal extension sepsis", "ent", 3),
    ("severe acute pancreatitis necrosis infected shock", "abdominal", 3),
    ("ischaemic colitis bloody diarrhoea peritonitis shock", "abdominal", 3),
    ("caecal volvulus massive distension peritonitis", "abdominal", 3),
    ("sigmoid volvulus obstruction distension peritonitis", "abdominal", 3),
    ("incarcerated hernia ischaemia peritonitis shock", "abdominal", 3),
    ("perforated peptic ulcer free air peritonitis shock", "abdominal", 3),
    ("severe Crohn perforated obstruction septic shock", "abdominal", 3),
    ("superior mesenteric artery occlusion gut infarct shock", "abdominal", 3),
    ("severe hepatitis fulminant failure encephalopathy", "gastro", 3),
    ("variceal bleed haematemesis massive blood haemorrhage", "gastro", 3),
    ("lower GI bleed massive haematochezia shock", "gastro", 3),
    ("ischaemic hepatitis shock liver failure", "organ_failure", 3),
    ("severe cholangitis Charcot triad shock sepsis", "abdominal", 3),
    ("acute severe colitis toxic megacolon sepsis", "gastro", 3),
    ("severe hypercalcaemia confusion seizure cardiac arrest", "metabolic", 3),
    ("severe hypermagnesaemia respiratory depression cardiac arrest", "metabolic", 3),
    ("severe hypophosphataemia respiratory failure paralysis", "metabolic", 3),
    ("Addisonian crisis glucocorticoid deficiency shock", "endocrine", 3),
    ("myxoedema coma hypothermia bradycardia unconscious", "endocrine", 3),
    ("diabetic mother neonate severe hypoglycaemia seizure", "pediatric", 3),
    ("congenital heart disease duct dependent collapse neonate", "pediatric", 3),
    ("pyloric stenosis severe dehydration alkalosis infant", "pediatric", 3),
    ("intussusception complete obstruction shock infant", "pediatric", 3),
    ("volvulus midgut malrotation infant shock peritonitis", "pediatric", 3),
    ("necrotising enterocolitis premature infant sepsis", "pediatric", 3),
    ("severe bronchiolitis infant RSV oxygen 70 intubation", "pediatric", 3),
    ("pertussis apnoea infant cyanosis post-tussive", "pediatric", 3),
    ("severe croup complete obstruction silent stridor", "pediatric", 3),
    ("epiglottitis child drooling tripod stridor", "pediatric", 3),
    ("child anaphylaxis food allergy collapse epinephrine", "pediatric", 3),
    ("neonatal jaundice severe bilirubin encephalopathy", "pediatric", 3),
    ("chest pain shortness breath sweating nausea", "cardiac", 2),
    ("severe abdominal pain vomiting blood", "abdominal", 2),
    ("broken bone visible fracture severe pain", "fracture", 2),
    ("deep cut bleeding heavily arterial", "laceration", 2),
    ("high fever 104 febrile seizure risk", "fever", 2),
    ("severe asthma cannot complete sentence", "respiratory", 2),
    ("diabetic emergency low sugar shaking confused", "diabetic", 2),
    ("severe allergic hives difficulty breathing", "allergic_reaction", 2),
    ("road accident multiple injuries bleeding conscious", "accident", 2),
    ("fall height back pain cannot move", "trauma", 2),
    ("severe burn hands arms blistering", "burns", 2),
    ("pregnancy heavy bleeding third trimester", "obstetric", 2),
    ("self harm wrist bleeding severe", "psychiatric", 2),
    ("electric shock burns hands confused", "electric", 2),
    ("poisoning chemicals vomiting blood conscious", "poisoning", 2),
    ("appendicitis severe right lower pain fever", "abdominal", 2),
    ("kidney stone excruciating flank vomiting", "abdominal", 2),
    ("hypertensive crisis very high pressure headache", "cardiac", 2),
    ("severe dehydration confusion not urinating elderly", "gastro", 2),
    ("dislocated shoulder severe cannot move", "injury", 2),
    ("worst headache life vomiting", "neurological", 2),
    ("eye chemical splash vision loss", "eye", 2),
    ("dog bite deep bleeding", "injury", 2),
    ("skull fracture head injury confusion", "trauma", 2),
    ("spinal fall cannot feel legs", "trauma", 2),
    ("pneumonia high fever oxygen low", "respiratory", 2),
    ("gallbladder attack fever jaundice pain", "abdominal", 2),
    ("panic attack chest pain numbness", "psychiatric", 2),
    ("heat stroke confusion seizure risk", "environmental", 2),
    ("severe food poisoning bloody diarrhea fever", "gastro", 2),
    ("broken leg femur cannot stand severe", "fracture", 2),
    ("facial fracture eye cannot open", "fracture", 2),
    ("rib fracture chest pain breathing", "fracture", 2),
    ("pelvic fracture cannot walk accident", "fracture", 2),
    ("compound fracture bone through skin", "fracture", 2),
    ("face forehead arterial bleed heavy", "laceration", 2),
    ("abdominal knife wound conscious bleeding", "laceration", 2),
    ("scalp wound profuse bleeding head", "laceration", 2),
    ("finger amputation partial tourniquet", "laceration", 2),
    ("burn face airway blistering", "burns", 2),
    ("chemical burn eyes vision affected", "burns", 2),
    ("electrical burn hands entry exit", "burns", 2),
    ("heart attack ECG changes chest pain", "cardiac", 2),
    ("unstable angina rest pain nitrates failed", "cardiac", 2),
    ("rapid AF palpitations dizzy breathless", "cardiac", 2),
    ("severe bradycardia rate 30 fainting", "cardiac", 2),
    ("pulmonary edema pink frothy breathless", "cardiac", 2),
    ("pericarditis chest pain worse lying fever", "cardiac", 2),
    ("DVT calf swollen red hot painful", "vascular", 2),
    ("peripheral artery occlusion leg cold pale", "vascular", 2),
    ("stroke face droop arm weak speech slurred", "stroke", 2),
    ("TIA symptoms resolving now", "stroke", 2),
    ("severe vertigo cannot stand vomiting", "neurological", 2),
    ("acute glaucoma severe eye pain halos", "eye", 2),
    ("retinal detachment flashing curtain vision loss", "eye", 2),
    ("orbital cellulitis swollen red fever", "eye", 2),
    ("epiglottitis drooling fever stridor", "ent", 2),
    ("peritonsillar abscess cannot open mouth", "ent", 2),
    ("mastoiditis ear swelling fever pain", "ent", 2),
    ("severe posterior nosebleed not stopping", "ent", 2),
    ("acute urinary retention cannot urinate pain", "urological", 2),
    ("testicular torsion sudden severe nausea", "urological", 2),
    ("ectopic one sided pain bleeding shoulder", "obstetric", 2),
    ("premature labour 28 weeks membranes ruptured", "obstetric", 2),
    ("postpartum hemorrhage heavy after delivery", "obstetric", 2),
    ("child medication ingestion unknown quantity", "pediatric", 2),
    ("child severe croup stridor distress", "pediatric", 2),
    ("child broken arm fall deformity", "pediatric", 2),
    ("elderly fall hip cannot weight bear", "injury", 2),
    ("elderly sudden confusion possible stroke", "neurological", 2),
    ("alcohol withdrawal seizure tremors hallucinations", "psychiatric", 2),
    ("acute psychosis aggressive threatening", "psychiatric", 2),
    ("suicidal patient with plan and means", "psychiatric", 2),
    ("snake bite swelling spreading numbness", "poisoning", 2),
    ("scorpion sting breathing difficulty", "poisoning", 2),
    ("carbon monoxide headache confusion multiple", "poisoning", 2),
    ("pesticide ingestion seizure salivation", "poisoning", 2),
    ("hyperthyroidism crisis rapid heart agitation", "endocrine", 2),
    ("severe hypoglycemia glucose 40 shaking confused", "diabetic", 2),
    ("DKA fruity breath vomiting confused", "diabetic", 2),
    ("crush syndrome trapped hours dark urine", "trauma", 2),
    ("blast injury explosion multiple wounds", "trauma", 2),
    ("hypothermia conscious shivering core low", "environmental", 2),
    ("heat exhaustion sweating weakness rapid pulse", "environmental", 2),
    ("altitude sickness severe headache ataxia", "environmental", 2),
    ("severe laceration thigh femoral region", "laceration", 2),
    ("penetrating chest wound sucking conscious", "trauma", 2),
    ("open fracture contaminated wound", "fracture", 2),
    ("severe concussion vomiting confused amnesia", "neurological", 2),
    ("epidural hematoma lucid interval worsening", "neurological", 2),
    ("acute meningism fever neck stiffness photophobia", "infection", 2),
    ("encephalitis high fever confusion seizure", "infection", 2),
    ("brain abscess fever headache focal signs", "infection", 2),
    ("spinal epidural abscess back pain fever paralysis", "infection", 2),
    ("necrotising fasciitis spreading rapidly fever shock", "infection", 2),
    ("fournier gangrene perineum spreading gas", "infection", 2),
    ("Ludwig angina early floor mouth swelling", "ent", 2),
    ("severe otitis externa canal swollen shut fever", "ent", 2),
    ("acute mastoiditis swelling behind ear fever", "ent", 2),
    ("severe epistaxis posterior pack required", "ent", 2),
    ("acute stridor in adult new onset", "ent", 2),
    ("severe obstructive sleep apnea desaturation", "respiratory", 2),
    ("haemoptysis significant volume blood", "respiratory", 2),
    ("spontaneous pneumothorax breathless one sided", "respiratory", 2),
    ("pleural effusion massive breathless at rest", "respiratory", 2),
    ("severe COPD exacerbation CO2 retaining confused", "respiratory", 2),
    ("severe pneumonitis aspiration oxygen drop", "respiratory", 2),
    ("pulmonary contusion post trauma breathless", "respiratory", 2),
    ("flail segment paradoxical breathing post trauma", "trauma", 2),
    ("severe anemia hemoglobin 5 breathless palpitations", "hematological", 2),
    ("sickle cell acute chest breathless fever", "hematological", 2),
    ("immune thrombocytopenia platelet 5 bleeding", "hematological", 2),
    ("haemolytic crisis jaundice dark urine breathless", "hematological", 2),
    ("anticoagulant overdose bleeding multiple sites", "hematological", 2),
    ("severe septic arthritis joint red hot immobile fever", "infection", 2),
    ("osteomyelitis bone pain fever high CRP", "infection", 2),
    ("severe pyelonephritis rigors fever loin tender", "infection", 2),
    ("complicated UTI upper tract fever confusion elderly", "infection", 2),
    ("meningitis bacterial adult severe fever stiff neck", "infection", 2),
    ("severe cellulitis limb threatening spreading", "infection", 2),
    ("compartment syndrome severe pain passive stretch", "injury", 2),
    ("acute limb ischaemia pale cold painful pulseless", "vascular", 2),
    ("ruptured baker cyst severe calf swelling pain", "vascular", 2),
    ("varicose vein rupture spurting blood leg", "vascular", 2),
    ("subclavian steal syncope arm exercise pain", "vascular", 2),
    ("severe Raynaud crisis digital ischaemia pain", "vascular", 2),
    ("severe epistaxis hypertension not controlled", "ent", 2),
    ("foreign body nose child distressed swelling", "ent", 2),
    ("button battery ear nose urgent removal", "pediatric", 2),
    ("foreign body airway partial obstruction child", "pediatric", 2),
    ("child drowning swimming pool conscious coughing", "drowning", 2),
    ("child head injury loss consciousness brief", "pediatric", 2),
    ("child severe gastroenteritis dehydration", "pediatric", 2),
    ("child diabetic DKA vomiting confused", "pediatric", 2),
    ("severe neonatal jaundice bilirubin rising", "pediatric", 2),
    ("infant apnoea episode brief monitored", "pediatric", 2),
    ("child limp fever septic arthritis concern", "pediatric", 2),
    ("child severe eczema infected widespread", "pediatric", 2),
    ("child anaphylaxis mild epinephrine given improving", "pediatric", 2),
    ("adolescent overdose paracetamol hours ago", "poisoning", 2),
    ("adolescent self harm deep laceration", "psychiatric", 2),
    ("severe eating disorder collapse electrolyte", "psychiatric", 2),
    ("acute first episode psychosis agitated", "psychiatric", 2),
    ("severe OCD crisis cannot function distress", "psychiatric", 2),
    ("PTSD flashback dissociation unsafe behaviour", "psychiatric", 2),
    ("severe domestic violence injuries multiple", "trauma", 2),
    ("sexual assault acute injuries distress", "trauma", 2),
    ("elderly abuse bruising malnutrition dehydration", "injury", 2),
    ("refugee severe malnutrition oedema weakness", "general", 2),
    ("traveller malaria fever rigors returning", "infection", 2),
    ("typhoid severe fever confusion rash", "infection", 2),
    ("dengue fever severe platelet drop bleeding", "infection", 2),
    ("leptospirosis jaundice renal failure fever", "infection", 2),
    ("rabies exposure unprovoked bite wound", "infection", 2),
    ("tetanus jaw lock progressive spasm fever", "infection", 2),
    ("botulism descending paralysis diplopia", "infection", 2),
    ("severe giardia dehydration weight loss", "infection", 2),
    ("amoebic dysentery bloody diarrhea fever severe", "infection", 2),
    ("severe athlete's foot cellulitis spreading", "infection", 2),
    ("herpes encephalitis fever confusion agitation", "infection", 2),
    ("HIV AIDS opportunistic infection PCP breathless", "infection", 2),
    ("tuberculosis haemoptysis weight loss night sweats", "infection", 2),
    ("severe COVID pneumonia oxygen dropping", "respiratory", 2),
    ("multisystem inflammatory child Kawasaki shock", "pediatric", 2),
    ("severe juvenile arthritis systemic fever rash", "pediatric", 2),
    ("child intussusception screaming pain intermittent", "pediatric", 2),
    ("child pyloric projectile vomiting dehydrated", "pediatric", 2),
    ("severe neonatal hypoglycaemia seizure", "pediatric", 2),
    ("child maltreatment suspicious injury pattern", "pediatric", 2),
    ("adolescent eating disorder severe electrolyte", "psychiatric", 2),
    ("severe postnatal depression psychosis", "psychiatric", 2),
    ("bipolar mania dangerous behaviour impulsive", "psychiatric", 2),
    ("severe alcohol liver failure jaundice confused", "gastro", 2),
    ("acute cholecystitis fever RUQ pain positive murphy", "abdominal", 2),
    ("severe diverticulitis perforation risk fever", "abdominal", 2),
    ("acute pancreatitis amylase high severe pain", "abdominal", 2),
    ("small bowel obstruction vomiting distension", "abdominal", 2),
    ("large bowel obstruction distension constipation", "abdominal", 2),
    ("ischaemic colitis pain after eating bloody diarrhoea", "abdominal", 2),
    ("severe IBD flare bloody diarrhoea weight loss", "gastro", 2),
    ("haematemesis moderate coffee ground vomiting", "gastro", 2),
    ("melaena dark tarry stool significant", "gastro", 2),
    ("rectal bleeding significant fresh red", "gastro", 2),
    ("severe jaundice bilirubin rapidly rising", "gastro", 2),
    ("acute hepatitis A severe vomiting jaundice", "gastro", 2),
    ("Budd Chiari acute liver congestion shock", "gastro", 2),
    ("severe renal colic stone obstructing fever", "urological", 2),
    ("urosepsis fever confusion hypotension", "urological", 2),
    ("acute prostatitis fever perineal pain", "urological", 2),
    ("penile fracture snap sound immediate swelling", "urological", 2),
    ("severe paraphimosis pain ischaemia", "urological", 2),
    ("phimosis urinary retention severe", "urological", 2),
    ("severe endometriosis peritoneal involvement", "obstetric", 2),
    ("miscarriage heavy bleeding pain significant", "obstetric", 2),
    ("severe morning sickness HG hospitalisation", "obstetric", 2),
    ("threatened preterm labour contractions", "obstetric", 2),
    ("foetal movement reduced concern", "obstetric", 2),
    ("severe PMS PMDD crisis psychiatric", "obstetric", 2),
    ("severe menorrhagia anaemia breathless", "obstetric", 2),
    ("ovarian hyperstimulation IVF severe ascites", "obstetric", 2),
    ("cervical ectopic pregnancy rupture risk", "obstetric", 2),
    ("interstitial pregnancy rupture haemorrhage", "obstetric", 2),
    ("severe hyperemesis electrolyte Wernicke risk", "obstetric", 2),
    ("abruption minor bleeding uterine tenderness", "obstetric", 2),
    ("vasa praevia bleeding foetal distress", "obstetric", 2),
    ("severe pre-eclampsia proteinuria hypertension", "obstetric", 2),
    ("HELLP syndrome thrombocytopenia liver enzymes", "obstetric", 2),
    ("chorioamnionitis fever maternal foetal tachycardia", "obstetric", 2),
    ("retained placenta bleeding post delivery", "obstetric", 2),
    ("perineal tear fourth degree repair needed", "obstetric", 2),
    ("mastitis abscess fever severe breast pain", "obstetric", 2),
    ("severe postnatal haemorrhage secondary", "obstetric", 2),
    ("newborn jaundice day one haemolytic", "pediatric", 2),
    ("infant fever under 3 months serious concern", "pediatric", 2),
    ("child kawasaki disease fever rash", "pediatric", 2),
    ("child HSP abdominal pain rash joints", "pediatric", 2),
    ("child nephrotic syndrome oedema protein", "pediatric", 2),
    ("child nephritic haematuria hypertension", "pediatric", 2),
    ("child juvenile diabetes new diagnosis", "pediatric", 2),
    ("child coeliac crisis severe failure thrive", "pediatric", 2),
    ("child appendicitis right iliac fossa fever", "pediatric", 2),
    ("child malrotation bile vomiting shock", "pediatric", 2),
    ("SCFE slipped capital femoral epiphysis limp", "pediatric", 2),
    ("Perthes disease limp pain hip child", "pediatric", 2),
    ("transient synovitis hip pain child fever low", "pediatric", 2),
    ("Osgood-Schlatter severe knee pain adolescent", "musculoskeletal", 2),
    ("growing pains severe bilateral legs night", "pediatric", 2),
    ("acute rheumatic fever joints fever carditis", "infection", 2),
    ("osteosarcoma pathological fracture pain swelling", "musculoskeletal", 2),
    ("septic arthritis joint hot red immobile fever", "infection", 2),
    ("moderate fever headache body ache fatigue", "fever", 1),
    ("sprained ankle swelling moderate pain", "injury", 1),
    ("vomiting diarrhea dehydration fluids", "gastro", 1),
    ("mild chest pain no breathlessness", "cardiac", 1),
    ("cut bleeding moderate stitches maybe", "laceration", 1),
    ("back pain spasm cannot walk well", "musculoskeletal", 1),
    ("mild allergic rash hives no breathing", "allergic_reaction", 1),
    ("UTI burning pain fever", "infection", 1),
    ("ear pain infection discharge fever", "infection", 1),
    ("tooth pain swelling abscess", "dental", 1),
    ("eye injury moderate blurred vision", "eye", 1),
    ("mild asthma inhaler not fully working", "respiratory", 1),
    ("anxiety hyperventilating tingling", "psychiatric", 1),
    ("nosebleed heavy ten minutes", "ent", 1),
    ("knee injury swelling limp", "injury", 1),
    ("food poisoning vomiting cramps moderate", "gastro", 1),
    ("sinusitis facial pain pressure headache", "ent", 1),
    ("wrist fracture fall swelling possible", "fracture", 1),
    ("chest infection fever breathing harder", "respiratory", 1),
    ("migraine moderate throbbing light sensitive", "neurological", 1),
    ("shoulder pain cannot lift arm", "musculoskeletal", 1),
    ("skin infection spreading redness fever", "infection", 1),
    ("moderate burn blistering second degree", "burns", 1),
    ("fainting brief now awake", "neurological", 1),
    ("first trimester bleeding cramping", "obstetric", 1),
    ("high blood pressure headache dizzy", "cardiac", 1),
    ("child fever 102 crying not eating", "fever", 1),
    ("moderate allergic face swelling no throat", "allergic_reaction", 1),
    ("hip elderly fall moderate pain", "injury", 1),
    ("abdominal cramps diarrhea fever low", "gastro", 1),
    ("cellulitis leg redness spreading fever", "infection", 1),
    ("shingles painful rash burning one side", "infection", 1),
    ("gout big toe severe red swollen", "musculoskeletal", 1),
    ("tennis elbow severe cannot grip", "musculoskeletal", 1),
    ("sciatica shooting pain down leg", "musculoskeletal", 1),
    ("frozen shoulder cannot move pain", "musculoskeletal", 1),
    ("plantar fasciitis heel pain morning", "musculoskeletal", 1),
    ("concussion moderate headache dizzy confused", "neurological", 1),
    ("Bell palsy sudden facial droop", "neurological", 1),
    ("carpal tunnel numbness hand night", "neurological", 1),
    ("renal colic moderate flank blood urine", "urological", 1),
    ("UTI elderly confusion fever", "infection", 1),
    ("prostatitis pelvic pain urinating fever", "urological", 1),
    ("ovarian cyst rupture moderate pain", "obstetric", 1),
    ("endometriosis severe period pain vomiting", "obstetric", 1),
    ("PID lower pain fever discharge", "obstetric", 1),
    ("hyperemesis vomiting pregnancy cannot eat", "obstetric", 1),
    ("child ear infection pain fever", "pediatric", 1),
    ("child strep throat fever swollen glands", "pediatric", 1),
    ("child vomiting dehydration moderate", "pediatric", 1),
    ("elderly UTI confusion moderate", "infection", 1),
    ("elderly fall bruising no fracture", "injury", 1),
    ("moderate depression cannot function", "psychiatric", 1),
    ("alcohol intoxication vomiting aspiration risk", "psychiatric", 1),
    ("drug withdrawal sweating shaking anxious", "psychiatric", 1),
    ("moderate asthma nebuliser slowly", "respiratory", 1),
    ("pleural effusion breathless exertion", "respiratory", 1),
    ("bronchitis cough fever moderate", "respiratory", 1),
    ("laryngitis hoarse cannot speak", "ent", 1),
    ("tonsillitis severe throat fever swallowing", "ent", 1),
    ("vertigo moderate nausea cannot drive", "neurological", 1),
    ("diabetic glucose high thirsty tired", "diabetic", 1),
    ("hyperthyroidism palpitations sweating anxious", "endocrine", 1),
    ("hypothyroidism fatigue cold cannot function", "endocrine", 1),
    ("anemia fatigue breathless pale", "hematological", 1),
    ("moderate dehydration dry mouth dizzy", "gastro", 1),
    ("gastroenteritis vomiting diarrhea cramps", "gastro", 1),
    ("peptic ulcer burning stomach empty", "gastro", 1),
    ("IBD flare cramping diarrhea", "gastro", 1),
    ("hepatitis jaundice fatigue moderate", "gastro", 1),
    ("skin infection impetigo spreading face", "skin", 1),
    ("contact dermatitis severe itching rash", "skin", 1),
    ("urticaria widespread hives moderate", "skin", 1),
    ("abscess painful fluctuant swelling fever", "infection", 1),
    ("infected wound tracking lines fever", "infection", 1),
    ("moderate extensive sunburn blistering", "burns", 1),
    ("chemical eye moderate irritation blur", "eye", 1),
    ("conjunctivitis purulent discharge pain", "eye", 1),
    ("moderate head injury conscious headache", "trauma", 1),
    ("rib bruising pain breathing moderate", "injury", 1),
    ("whiplash neck pain stiffness after", "injury", 1),
    ("moderate laceration forearm needs sutures", "laceration", 1),
    ("knee ligament tear moderate swelling", "injury", 1),
    ("Achilles tendon rupture snap walking", "injury", 1),
    ("hamstring tear severe pain thigh sport", "injury", 1),
    ("groin strain severe pain kicking", "injury", 1),
    ("calf strain tear sudden pain running", "injury", 1),
    ("quadriceps tear sudden pain stair", "injury", 1),
    ("rotator cuff tear shoulder night pain", "musculoskeletal", 1),
    ("moderate TMJ jaw pain clicking locking", "dental", 1),
    ("dry socket severe pain after extraction", "dental", 1),
    ("cracked tooth severe sharp pain cold", "dental", 1),
    ("dental trauma knocked out tooth sport", "dental", 1),
    ("moderate sinusitis antibiotics needed", "ent", 1),
    ("foreign body ear child distressed", "ent", 1),
    ("foreign body nose child pushing", "ent", 1),
    ("moderate epistaxis anterior silver nitrate", "ent", 1),
    ("moderate otitis media child pain fever", "ent", 1),
    ("glue ear moderate hearing loss child", "ent", 1),
    ("moderate tinnitus sudden onset one ear", "ent", 1),
    ("sudden hearing loss one ear no pain", "ent", 1),
    ("moderate hypoglycemia glucose 60 dizzy", "diabetic", 1),
    ("insulin reaction moderate sweating shaking", "diabetic", 1),
    ("moderate hyperglycemia glucose 300 thirst", "diabetic", 1),
    ("moderate thyroid swelling pain goitre", "endocrine", 1),
    ("adrenal insufficiency fatigue low pressure", "endocrine", 1),
    ("moderate Cushing moon face weight gain", "endocrine", 1),
    ("PCOS moderate irregular bleeding pain", "obstetric", 1),
    ("moderate fibroids heavy period anaemia", "obstetric", 1),
    ("cervical erosion moderate bleeding contact", "obstetric", 1),
    ("moderate breast pain cyclical tenderness", "obstetric", 1),
    ("moderate pelvic pain IUD strings missing", "obstetric", 1),
    ("moderate vulvovaginitis discharge itch pain", "obstetric", 1),
    ("moderate urinary incontinence affecting life", "urological", 1),
    ("moderate BPH difficulty passing urine", "urological", 1),
    ("renal calculi moderate pain no fever", "urological", 1),
    ("haematuria microscopic moderate investigation", "urological", 1),
    ("moderate erectile dysfunction investigation", "urological", 1),
    ("moderate varicocele pain swelling", "urological", 1),
    ("moderate epididymo-orchitis pain swelling fever", "urological", 1),
    ("UTI recurrent moderate culture needed", "urological", 1),
    ("moderate skin psoriasis flare extensive", "skin", 1),
    ("moderate eczema infected weeping", "skin", 1),
    ("moderate acne nodulocystic pain", "skin", 1),
    ("moderate rosacea facial flushing eye", "skin", 1),
    ("moderate skin fungal widespread", "skin", 1),
    ("moderate alopecia rapid hair loss", "skin", 1),
    ("moderate leg ulcer venous sloughy", "skin", 1),
    ("moderate pressure sore grade three", "skin", 1),
    ("moderate Raynaud digital colour change pain", "vascular", 1),
    ("moderate claudication pain walking distance", "vascular", 1),
    ("moderate varicose veins aching swollen", "vascular", 1),
    ("moderate lymphoedema limb swelling", "vascular", 1),
    ("moderate chest wall pain musculoskeletal", "musculoskeletal", 1),
    ("moderate fibromyalgia widespread pain fatigue", "musculoskeletal", 1),
    ("moderate polymyalgia shoulder hip girdle", "musculoskeletal", 1),
    ("moderate rheumatoid arthritis flare joints", "musculoskeletal", 1),
    ("moderate osteoarthritis knee pain function", "musculoskeletal", 1),
    ("moderate ankylosing spondylitis back stiff", "musculoskeletal", 1),
    ("moderate lupus flare joint rash fatigue", "musculoskeletal", 1),
    ("moderate psoriatic arthritis joint skin", "musculoskeletal", 1),
    ("moderate gout flare multiple joints", "musculoskeletal", 1),
    ("moderate Raynaud pain cold change colour", "musculoskeletal", 1),
    ("moderate Crohn abdominal diarrhoea weight", "gastro", 1),
    ("moderate ulcerative colitis bloody diarrhoea", "gastro", 1),
    ("moderate IBS severe cramping diarrhoea", "gastro", 1),
    ("moderate coeliac undiagnosed weight loss", "gastro", 1),
    ("moderate GORD severe reflux erosive", "gastro", 1),
    ("moderate haemorrhoids prolapsed bleeding", "gastro", 1),
    ("moderate anal fissure severe pain bleeding", "gastro", 1),
    ("moderate constipation impaction elderly", "gastro", 1),
    ("moderate dysphagia difficulty swallowing solids", "gastro", 1),
    ("moderate nausea persistent vomiting weight loss", "gastro", 1),
    ("moderate jaundice mild investigation needed", "gastro", 1),
    ("moderate iron deficiency fatigue palpitations", "hematological", 1),
    ("moderate B12 deficiency neurological tingling", "hematological", 1),
    ("moderate folate deficiency macrocytic anaemia", "hematological", 1),
    ("moderate polycythaemia headache plethora", "hematological", 1),
    ("moderate lymphoma night sweats weight loss", "hematological", 1),
    ("moderate anxiety generalised affecting work", "psychiatric", 1),
    ("moderate OCD intrusive thoughts affecting", "psychiatric", 1),
    ("moderate PTSD flashbacks insomnia", "psychiatric", 1),
    ("moderate bipolar hypomania functioning", "psychiatric", 1),
    ("moderate eating restriction weight concern", "psychiatric", 1),
    ("moderate grief complicated affecting function", "psychiatric", 1),
    ("moderate burnout exhaustion depersonalisation", "psychiatric", 1),
    ("moderate insomnia chronic affecting health", "psychiatric", 1),
    ("moderate ADHD adult affecting work", "psychiatric", 1),
    ("moderate autism sensory crisis meltdown", "psychiatric", 1),
    ("moderate concussion symptoms two weeks", "neurological", 1),
    ("moderate neuropathy peripheral feet burning", "neurological", 1),
    ("moderate multiple sclerosis relapse", "neurological", 1),
    ("moderate Parkinson tremor affecting function", "neurological", 1),
    ("moderate epilepsy breakthrough seizure", "neurological", 1),
    ("moderate migraine frequent affecting life", "neurological", 1),
    ("moderate cluster headache severe one sided", "neurological", 1),
    ("moderate essential tremor hands function", "neurological", 1),
    ("moderate chronic fatigue post viral", "general", 1),
    ("moderate long COVID breathless fatigue", "respiratory", 1),
    ("moderate post operative wound infection", "infection", 1),
    ("moderate urinary retention partial BPH", "urological", 1),
    ("moderate haematuria visible frank blood", "urological", 1),
    ("moderate loin pain hydronephrosis", "urological", 1),
    ("moderate scrotal swelling epididymis", "urological", 1),
    ("moderate penile discharge urethritis STI", "urological", 1),
    ("STI gonorrhoea severe urethritis discharge", "infection", 1),
    ("syphilis secondary rash systemic", "infection", 1),
    ("HIV new diagnosis investigation", "infection", 1),
    ("moderate warts extensive treatment", "skin", 1),
    ("herpes genital outbreak severe primary", "infection", 1),
    ("moderate pelvic pain PID investigation", "infection", 1),
    ("moderate endometritis post delivery fever", "obstetric", 1),
    ("moderate wound dehiscence post surgery", "injury", 1),
    ("moderate seroma post surgery collection", "injury", 1),
    ("moderate haematoma post injury swelling", "injury", 1),
    ("moderate tendinopathy Achilles pain sport", "musculoskeletal", 1),
    ("moderate stress fracture foot pain running", "fracture", 1),
    ("moderate shin splints pain bilateral", "musculoskeletal", 1),
    ("moderate patellofemoral pain stairs running", "musculoskeletal", 1),
    ("moderate ITB syndrome lateral knee pain", "musculoskeletal", 1),
    ("moderate subacromial impingement shoulder", "musculoskeletal", 1),
    ("moderate de Quervain thumb wrist pain", "musculoskeletal", 1),
    ("moderate trigger finger catching locking", "musculoskeletal", 1),
    ("moderate Dupuytren contracture finger", "musculoskeletal", 1),
    ("moderate ganglion wrist swelling ache", "musculoskeletal", 1),
    ("moderate bunion hallux pain footwear", "musculoskeletal", 1),
    ("moderate Morton neuroma foot pain walking", "musculoskeletal", 1),
    ("moderate tarsal tunnel foot tingling", "musculoskeletal", 1),
    ("moderate metatarsalgia forefoot pain", "musculoskeletal", 1),
    ("moderate hip flexor strain pain walking", "musculoskeletal", 1),
    ("moderate sacroiliac joint pain one side", "musculoskeletal", 1),
    ("moderate facet joint pain back extension", "musculoskeletal", 1),
    ("moderate disc prolapse leg pain back", "musculoskeletal", 1),
    ("moderate spinal stenosis leg pain walking", "musculoskeletal", 1),
    ("moderate spondylolisthesis back pain", "musculoskeletal", 1),
    ("moderate scoliosis back pain posture", "musculoskeletal", 1),
    ("moderate kyphosis back pain posture", "musculoskeletal", 1),
    ("moderate torticollis neck pain spasm", "musculoskeletal", 1),
    ("moderate cervicogenic headache neck", "musculoskeletal", 1),
    ("moderate thoracic outlet tingling arm", "musculoskeletal", 1),
    ("moderate cubital tunnel elbow tingling", "musculoskeletal", 1),
    ("moderate meralgia paresthetica thigh numb", "musculoskeletal", 1),
    ("moderate trochanteric bursitis hip pain", "musculoskeletal", 1),
    ("moderate olecranon bursitis elbow swelling", "musculoskeletal", 1),
    ("moderate prepatellar bursitis knee swelling", "musculoskeletal", 1),
    ("moderate medial epicondylitis golfer elbow", "musculoskeletal", 1),
    ("moderate lateral epicondylitis tennis elbow", "musculoskeletal", 1),
    ("mild headache slight fever fatigue", "fever", 0),
    ("minor cut bleeding stopped", "laceration", 0),
    ("mild stomach ache nausea", "gastro", 0),
    ("sore throat mild cough no fever", "respiratory", 0),
    ("minor bruise slight pain", "injury", 0),
    ("mild back pain sitting long", "musculoskeletal", 0),
    ("slight dizziness stood up fast", "general", 0),
    ("mild rash no breathing fever", "skin", 0),
    ("minor burn redness first degree", "burns", 0),
    ("mild anxiety stress work", "psychiatric", 0),
    ("common cold runny nose sneezing", "respiratory", 0),
    ("mild muscle cramp leg", "musculoskeletal", 0),
    ("minor eye irritation redness", "eye", 0),
    ("mild indigestion heartburn after eating", "gastro", 0),
    ("slight fever fatigue no symptoms", "fever", 0),
    ("mild toothache no swelling", "dental", 0),
    ("minor sprain mild walking possible", "injury", 0),
    ("mild earache no discharge", "ent", 0),
    ("dry skin mild itching", "skin", 0),
    ("mild constipation no pain", "gastro", 0),
    ("slight breathless climbing unfit", "respiratory", 0),
    ("mild joint pain arthritis manageable", "musculoskeletal", 0),
    ("minor seasonal allergy sneezing", "allergic_reaction", 0),
    ("mild insomnia stress no physical", "psychiatric", 0),
    ("minor lip cut bleeding stopped", "laceration", 0),
    ("mild sunburn redness no blister", "burns", 0),
    ("slight nausea motion sickness", "gastro", 0),
    ("minor finger cut kitchen controlled", "laceration", 0),
    ("mild cold sore no symptoms", "skin", 0),
    ("slight fatigue overworked", "general", 0),
    ("mild hiccups persistent", "general", 0),
    ("minor paper cut minimal bleeding", "laceration", 0),
    ("mild bloating after eating", "gastro", 0),
    ("slight muscle soreness exercise", "musculoskeletal", 0),
    ("mild tension headache screen time", "neurological", 0),
    ("minor insect bite local itching", "skin", 0),
    ("mild period pain manageable", "obstetric", 0),
    ("slight sore throat no fever", "respiratory", 0),
    ("mild hay fever itchy eyes", "allergic_reaction", 0),
    ("minor toe stubbed mild pain", "injury", 0),
    ("mild diarrhea one episode", "gastro", 0),
    ("slight wrist pain repetitive mild", "musculoskeletal", 0),
    ("minor elbow scrape graze clean", "laceration", 0),
    ("mild knee pain running overuse", "musculoskeletal", 0),
    ("slight chest tightness anxiety resolved", "psychiatric", 0),
    ("mild cold symptoms working", "respiratory", 0),
    ("minor shin bruise playing sport", "injury", 0),
    ("mild acid reflux occasional", "gastro", 0),
    ("slight lower back ache lifted", "musculoskeletal", 0),
    ("minor chapped lips dry weather", "skin", 0),
    ("mild eye strain computer work", "eye", 0),
    ("slight ankle stiffness morning", "musculoskeletal", 0),
    ("minor scalp irritation dandruff", "skin", 0),
    ("mild thirst frequent urination", "general", 0),
    ("slight nosebleed stopped quickly", "ent", 0),
    ("minor abrasion knee fell graze", "laceration", 0),
    ("mild flatulence bloating dietary", "gastro", 0),
    ("slight finger swelling ring", "injury", 0),
    ("mild cough no fever dry", "respiratory", 0),
    ("minor mouth ulcer eating manageable", "dental", 0),
    ("slight hip stiffness sitting elderly", "musculoskeletal", 0),
    ("mild travel sickness nausea", "gastro", 0),
    ("minor eyelid twitch stress", "eye", 0),
    ("slight foot pain new shoes blister", "injury", 0),
    ("mild acne breakout no infection", "skin", 0),
    ("slight headache dehydration water helps", "general", 0),
    ("minor hangnail slightly sore", "skin", 0),
    ("mild ear wax muffled no pain", "ent", 0),
    ("slight shoulder stiffness slept awkward", "musculoskeletal", 0),
    ("mild dry eyes irritation no pain", "eye", 0),
    ("minor heat rash mild itching", "skin", 0),
    ("slight dizziness orthostatic standing", "general", 0),
    ("mild snoring no symptoms day", "respiratory", 0),
    ("minor fingernail broken sore", "injury", 0),
    ("mild lip swelling spicy food", "allergic_reaction", 0),
    ("slight neck stiffness phone too long", "musculoskeletal", 0),
    ("minor bruise arm knocked table", "injury", 0),
    ("mild frequent urination no pain", "urological", 0),
    ("slight skin dryness flaking winter", "skin", 0),
    ("minor gum bleeding brushing", "dental", 0),
    ("mild tiredness long work day", "general", 0),
    ("slight ankle stiffness long walk", "musculoskeletal", 0),
    ("minor wrist click no pain", "musculoskeletal", 0),
    ("mild pimple forehead no fever", "skin", 0),
    ("slight stomach gurgling hunger", "gastro", 0),
    ("minor leg cramp night resolved", "musculoskeletal", 0),
    ("mild sensitivity tooth cold", "dental", 0),
    ("slight redness eye no discharge", "eye", 0),
    ("minor back stiffness morning resolved", "musculoskeletal", 0),
    ("mild sneezing dusty no symptoms", "respiratory", 0),
    ("slight thumb pain texting mild", "musculoskeletal", 0),
    ("minor ingrown toenail no infection", "skin", 0),
    ("mild appetite loss stress", "general", 0),
    ("slight palpitations caffeine resolved", "cardiac", 0),
    ("minor chafing walking redness mild", "skin", 0),
    ("mild forgetfulness stress tired", "general", 0),
    ("slight jaw clicking no pain", "dental", 0),
    ("minor splinter slightly sore visible", "injury", 0),
    ("mild bloating menstrual manageable", "obstetric", 0),
    ("slight rash behind ear no fever", "skin", 0),
    ("minor sunburn small area mild", "burns", 0),
    ("mild throat clearing no cough", "respiratory", 0),
    ("slight knee click stairs no pain", "musculoskeletal", 0),
    ("mild dry skin hands winter", "skin", 0),
    ("minor toenail discolouration no pain", "skin", 0),
    ("slight hip click walking no pain", "musculoskeletal", 0),
    ("mild scalp dryness flaking", "skin", 0),
    ("minor lip dryness cold weather", "skin", 0),
    ("slight eye twitching tired", "eye", 0),
    ("mild finger stiffness morning brief", "musculoskeletal", 0),
    ("minor forehead spot painful", "skin", 0),
    ("slight neck ache computer screen", "musculoskeletal", 0),
    ("mild thigh ache after exercise", "musculoskeletal", 0),
    ("minor heel pain morning brief", "musculoskeletal", 0),
    ("slight elbow ache desk work", "musculoskeletal", 0),
    ("mild wrist ache gaming long", "musculoskeletal", 0),
    ("minor shoulder ache painting", "musculoskeletal", 0),
    ("slight calf tightness after run", "musculoskeletal", 0),
    ("mild shin ache walking new shoes", "musculoskeletal", 0),
    ("minor groin ache stretching", "musculoskeletal", 0),
    ("slight buttock ache sitting hard chair", "musculoskeletal", 0),
    ("mild upper back ache slouching", "musculoskeletal", 0),
    ("minor mid back ache standing", "musculoskeletal", 0),
    ("slight lower back ache gardening", "musculoskeletal", 0),
    ("mild neck ache reading downward", "musculoskeletal", 0),
    ("minor jaw ache chewing tough food", "dental", 0),
    ("slight temple ache stress", "neurological", 0),
    ("mild sinus pressure no fever", "ent", 0),
    ("minor ear pressure altitude flight", "ent", 0),
    ("slight throat itch pollen", "respiratory", 0),
    ("mild runny nose cold weather", "respiratory", 0),
    ("minor eye watering wind outside", "eye", 0),
    ("slight eye dryness air conditioning", "eye", 0),
    ("mild ear ringing brief after loud", "ent", 0),
    ("minor nasal congestion dust allergy", "ent", 0),
    ("slight post nasal drip no fever", "ent", 0),
    ("mild hoarseness talking too much", "ent", 0),
    ("minor lip tingling cold sore coming", "skin", 0),
    ("slight skin sensitivity new soap", "skin", 0),
    ("mild nail brittleness breaking", "skin", 0),
    ("minor hair loss stress telogen", "skin", 0),
    ("slight skin darkening sun exposure", "skin", 0),
    ("mild stretch marks no symptoms", "skin", 0),
    ("minor varicose vein ache standing", "vascular", 0),
    ("slight leg heaviness standing long", "vascular", 0),
    ("mild ankle puffiness end of day", "vascular", 0),
    ("minor finger colour change cold brief", "vascular", 0),
    ("slight abdominal ache after meal", "gastro", 0),
    ("mild belching after eating no pain", "gastro", 0),
    ("minor hiccup after eating brief", "gastro", 0),
    ("slight nausea morning no vomiting", "gastro", 0),
    ("mild loose stool dietary change", "gastro", 0),
    ("minor abdominal gurgling hunger", "gastro", 0),
    ("slight weight fluctuation diet", "general", 0),
    ("mild fatigue poor sleep no symptoms", "general", 0),
    ("minor thirst normal activity", "general", 0),
    ("slight sweating mild exertion normal", "general", 0),
    ("mild temperature 99 feeling off", "fever", 0),
    ("minor cold chills no high fever", "fever", 0),
    ("slight body ache after long day", "fever", 0),
    ("mild generalised ache viral feeling", "fever", 0),
    ("minor post vaccination soreness arm", "injury", 0),
    ("slight injection site redness", "skin", 0),
    ("mild bruising blood thinner medication", "injury", 0),
    ("minor swelling ring finger tight", "injury", 0),
    ("slight numbness hand sleeping awkward", "neurological", 0),
    ("mild tingling foot sitting crossed", "neurological", 0),
    ("minor pins needles arm brief", "neurological", 0),
    ("slight lightheadedness brief standing", "neurological", 0),
    ("mild memory lapse stress tired", "neurological", 0),
    ("minor word finding difficulty tired", "neurological", 0),
    ("slight concentration difficulty stress", "psychiatric", 0),
    ("mild mood low brief passing", "psychiatric", 0),
    ("minor irritability tired hungry", "psychiatric", 0),
    ("slight social anxiety mild", "psychiatric", 0),
    ("mild worry generalised manageable", "psychiatric", 0),
    ("minor sadness passing grief normal", "psychiatric", 0),
    ("slight motivation low brief", "psychiatric", 0),
    ("mild stress exam work manageable", "psychiatric", 0),
    ("minor loneliness mild social", "psychiatric", 0),
    ("slight restlessness mild anxiety", "psychiatric", 0),
    ("mild urine colour dark drinking little", "urological", 0),
    ("minor urinary frequency after coffee", "urological", 0),
    ("slight urinary hesitancy morning brief", "urological", 0),
    ("mild scrotal ache after exercise brief", "urological", 0),
    ("minor vaginal dryness mild discomfort", "obstetric", 0),
    ("slight breast tenderness premenstrual", "obstetric", 0),
    ("mild menstrual cramp manageable", "obstetric", 0),
    ("minor lower abdominal twinge brief", "obstetric", 0),
    ("slight nipple sensitivity cold", "obstetric", 0),
    ("mild pelvic floor weakness mild", "obstetric", 0),
    ("minor vaginal discharge normal colour", "obstetric", 0),
    ("slight hormonal mood change cycle", "obstetric", 0),
    ("mild hot flush brief menopause", "obstetric", 0),
    ("minor libido change stress related", "obstetric", 0),
    ("slight child irritability teething", "pediatric", 0),
    ("mild child cough no fever night", "pediatric", 0),
    ("minor child runny nose cold", "pediatric", 0),
    ("slight child tummy ache wind", "pediatric", 0),
    ("mild child headache tired school", "pediatric", 0),
    ("minor child scraped knee playground", "pediatric", 0),
    ("slight child sore throat mild", "pediatric", 0),
    ("mild child ear ache no fever", "pediatric", 0),
    ("minor child eye sticky morning", "pediatric", 0),
    ("slight child nappy rash mild", "pediatric", 0),
    ("mild child constipation dietary", "pediatric", 0),
    ("minor child bruise arm fall mild", "pediatric", 0),
    ("slight child colic evening brief", "pediatric", 0),
    ("mild child growing pains mild night", "pediatric", 0),
    ("minor child hiccup persistent brief", "pediatric", 0),
    ("slight child lip bump knocked mild", "pediatric", 0),
    ("mild child finger jam door minor", "pediatric", 0),
    ("minor child insect bite local", "pediatric", 0),
    ("slight child sunburn mild redness", "pediatric", 0),
    ("mild child splinter visible remove", "pediatric", 0),
    ("minor elderly stiff joints morning", "musculoskeletal", 0),
    ("slight elderly balance mild dizzy", "general", 0),
    ("mild elderly appetite reduced no pain", "general", 0),
    ("minor elderly memory mild concern", "neurological", 0),
    ("slight elderly hearing mild loss", "ent", 0),
    ("mild elderly vision mild glasses", "eye", 0),
    ("minor elderly skin bruise easy", "skin", 0),
    ("slight elderly sleep difficulty mild", "psychiatric", 0),
    ("mild elderly foot pain walking", "musculoskeletal", 0),
    ("minor elderly hand tremor mild", "neurological", 0),
]
